import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { UebersichtComponent } from './uebersicht/uebersicht.component';
import { LoginComponent } from './login/login.component';

export const routes: Routes = [
  {
    path: '', redirectTo: 'login', pathMatch: 'full'
  },
  {
    path: 'login', component: LoginComponent
  }/*,
  {
    path: 'belege', component: BelegComponent
  },
  {
    path: 'einzahlung', component: EinzahlungComponent
  },
  {
    path: 'strichliste', component: StrichlisteComponent
  },
  {
    path: 'konto', component: KontoComponent
  }*/
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
