import { BrowserModule } from '@angular/platform-browser';
import { NgModule, LOCALE_ID } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { UebersichtComponent } from '@src/app/uebersicht/uebersicht.component';
import { KonsumComponent } from '@src/app/konsum/konsum.component';
import { KontoComponent } from '@src/app/konto/konto.component';
import { EinzahlungComponent } from '@src/app/einzahlung/einzahlung.component';
import { StrichlisteComponent } from '@src/app/strichliste/strichliste.component';
import { BelegComponent } from '@src/app/beleg/beleg.component';
import { MenueComponent } from '@src/app/menue/menue.component';
import { HttpClientModule } from '@angular/common/http';
import { LoginComponent } from '@src/app/login/login.component';

// Lokalisierung festlegen, um das Datum umformatieren zu können
import { registerLocaleData } from '@angular/common';
import localeDe from '@angular/common/locales/de';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';



@NgModule({
  declarations: [
    AppComponent,
    UebersichtComponent,
    KonsumComponent,
    KontoComponent,
    EinzahlungComponent,
    StrichlisteComponent,
    BelegComponent,
    MenueComponent,
    LoginComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    FormsModule
  ],
  providers: [{ provide: LOCALE_ID, useValue: "de" }],
  bootstrap: [AppComponent]
})
export class AppModule { 
  constructor() {
    registerLocaleData(localeDe);
  }
}
